yarnPath: .yarn/releases/yarn-4.6.0.cjs

logFilters:
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

packageExtensions:
    postcss-loader@*:
        peerDependencies:
            tailwindcss: "*"
    gatsby-plugin-postcss@*:
        peerDependencies:
            tailwindcss: "*"
    lmdb@*:
        peerDependencies:
            node-addon-api: "*"
    react-server-dom-webpack@*:
        peerDependencies:
            react: "^18.0.0"
            react-dom: "^18.0.0"
