yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
    postcss-loader@*:
        peerDependencies:
            tailwindcss: "*"
    gatsby-plugin-postcss@*:
        peerDependencies:
            tailwindcss: "*"
    lmdb@*:
        peerDependencies:
            node-addon-api: "*"
    react-server-dom-webpack@*:
        peerDependencies:
            react: "18.2.0"
            react-dom: "18.2.0"
