yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: pnp

packageExtensions:
    postcss-loader@*:
        peerDependencies:
            tailwindcss: "*"
    gatsby-plugin-postcss@*:
        peerDependencies:
            tailwindcss: "*"
    "react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825":
        peerDependencies:
            react: "^18.0.0"
