yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
    postcss-loader@*:
        peerDependencies:
            tailwindcss: "*"
    gatsby-plugin-postcss@*:
        peerDependencies:
            tailwindcss: "*"
    lmdb@*:
        peerDependencies:
            node-addon-api: "*"
